<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>rvar: The Random Variable Datatype • posterior</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="rvar: The Random Variable Datatype">
<meta property="og:description" content="posterior">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">posterior</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.6</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/index.html">Vignettes</a>
</li>
<li>
  <a href="../reference/index.html">Functions</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Other Packages
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="https://mc-stan.org/rstan">rstan</a>
    </li>
    <li>
      <a href="https://mc-stan.org/cmdstanr">cmdstanr</a>
    </li>
    <li>
      <a href="https://mc-stan.org/rstanarm">rstanarm</a>
    </li>
    <li>
      <a href="https://mc-stan.org/bayesplot">bayesplot</a>
    </li>
    <li>
      <a href="https://mc-stan.org/shinystan">shinystan</a>
    </li>
    <li>
      <a href="https://mc-stan.org/loo">loo</a>
    </li>
    <li>
      <a href="https://mc-stan.org/projpred">projpred</a>
    </li>
    <li>
      <a href="https://mc-stan.org/rstantools">rstantools</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://mc-stan.org">Stan</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://twitter.com/mcmc_stan">
    <span class="fas fa-twitter"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/stan-dev/posterior">
    <span class="fas fa-github"></span>
     
  </a>
</li>
<li>
  <a href="https://discourse.mc-stan.org/">
    <span class="fas fa-users"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="rvar_files/header-attrs-2.8/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>rvar: The Random Variable Datatype</h1>
                        <h4 class="author">Matthew Kay</h4>
            
            <h4 class="date">2021-05-22</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/stan-dev/posterior/blob/master/vignettes/rvar.Rmd"><code>vignettes/rvar.Rmd</code></a></small>
      <div class="hidden name"><code>rvar.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>This vignette describes the <code><a href="../reference/rvar.html">rvar()</a></code> datatype, a multidimensional, sample-based representation of random variables designed to act as much like base R arrays as possible (e.g., by supporting many math operators and functions). This format is also the basis of the <code><a href="../reference/draws_rvars.html">draws_rvars()</a></code> format.</p>
<p>The <code><a href="../reference/rvar.html">rvar()</a></code> datatype is inspired by the <a href="https://cran.r-project.org/package=rv">rv</a> package and <a href="https://doi.org/10.1007%2Fs11222-007-9020-4">Kerman and Gelman (2007)</a>, though with a slightly different backing format (multidimensional arrays). It is also designed to interoperate with vectorized distributions in the <a href="https://pkg.mitchelloharawild.com/distributional/">distributional</a> package, to be able to be used inside <code><a href="https://rdrr.io/r/base/data.frame.html">data.frame()</a></code>s and <code>tibble()</code>s, and to be used with distribution visualizations in the <a href="https://mjskay.github.io/ggdist/">ggdist</a> package.</p>
</div>
<div id="the-rvars-datatype" class="section level2">
<h2 class="hasAnchor">
<a href="#the-rvars-datatype" class="anchor"></a>The <code>rvars</code> datatype</h2>
<p>The <code><a href="../reference/rvar.html">rvar()</a></code> datatype is a wrapper around a multidimensional array where the first dimension is the number of draws in the random variable. The most direct way to create a random variable is to pass such an array to the <code><a href="../reference/rvar.html">rvar()</a></code> function.</p>
<p>For example, to create a “scalar” <code>rvar</code>, one would pass a one-dimensional array or a vector whose length (here <code>4000</code>) is the desired number of draws:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rvar.html">rvar</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">4000</span>, mean <span class="op">=</span> <span class="fl">1</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">x</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[1] mean ± sd:
## [1] 1 ± 1</code></pre>
<p>The default display of an <code>rvar</code> shows the mean and standard deviation of each element of the array.</p>
<p>We can create random vectors by adding an additional dimension beyond just the draws dimension to the input array:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">4</span>   <span class="co"># length of output vector</span>
<span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rvar.html">rvar</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">4000</span><span class="op">*</span><span class="va">n</span>, mean <span class="op">=</span> <span class="fl">1</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, dim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4000</span>, <span class="va">n</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="va">x</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[4] mean ± sd:
## [1] 1.01 ± 0.99  1.02 ± 0.99  0.98 ± 1.00  0.99 ± 1.02</code></pre>
<p>Or we can create a random matrix:</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">rows</span> <span class="op">&lt;-</span> <span class="fl">4</span>
<span class="va">cols</span> <span class="op">&lt;-</span> <span class="fl">3</span>
<span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rvar.html">rvar</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">4000</span> <span class="op">*</span> <span class="va">rows</span> <span class="op">*</span> <span class="va">cols</span>, mean <span class="op">=</span> <span class="fl">1</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, dim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4000</span>, <span class="va">rows</span>, <span class="va">cols</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="va">x</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[4,3] mean ± sd:
##      [,1]         [,2]         [,3]        
## [1,] 1.00 ± 0.98  1.00 ± 1.00  0.97 ± 1.00 
## [2,] 1.00 ± 1.01  1.01 ± 1.02  0.99 ± 0.99 
## [3,] 1.02 ± 1.01  0.99 ± 1.00  1.00 ± 0.99 
## [4,] 1.01 ± 1.01  1.02 ± 1.00  1.00 ± 1.01</code></pre>
<p>Or any array up to an arbitrary number of dimensions. The array backing an <code>rvar</code> can be accessed (and modified, with caution) via <code><a href="../reference/draws_of.html">draws_of()</a></code>:</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="fu"><a href="../reference/draws_of.html">draws_of</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##  num [1:4000, 1:4, 1:3] -0.6879 0.0448 0.3519 1.261 -0.2197 ...
##  - attr(*, "dimnames")=List of 3
##   ..$ : chr [1:4000] "1" "2" "3" "4" ...
##   ..$ : NULL
##   ..$ : NULL</code></pre>
<p>Manual construction and modification of <code>rvar</code>s in this way is not recommended unless you need it for performance reasons: several other higher-level interfaces to constructing and manipulating <code>rvar</code>s are described below.</p>
</div>
<div id="the-draws_rvars-datatype" class="section level2">
<h2 class="hasAnchor">
<a href="#the-draws_rvars-datatype" class="anchor"></a>The <code>draws_rvars</code> datatype</h2>
<p>The <code><a href="../reference/draws_rvars.html">draws_rvars()</a></code> datatype, like all <code>draws</code> datatypes in posterior, contains multiple variables in a joint sample from some distribution (e.g. a posterior or prior distribution).</p>
<p>Below is the <code><a href="../reference/example_draws.html">example_draws("multi_normal")</a></code> dataset converted into the <code><a href="../reference/draws_rvars.html">draws_rvars()</a></code> format. This dataset has 100 iterations from 4 chains from the posterior of a a 3-dimensional multivariate normal model. The <code>mu</code> variable is a mean vector of length 3 and the <code>Sigma</code> variable is a <span class="math inline">\(3 \times 3\)</span> covariance matrix:</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">post</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/draws_rvars.html">as_draws_rvars</a></span><span class="op">(</span><span class="fu"><a href="../reference/example_draws.html">example_draws</a></span><span class="op">(</span><span class="st">"multi_normal"</span><span class="op">)</span><span class="op">)</span>
<span class="va">post</span></code></pre></div>
<pre><code>## # A draws_rvars: 100 iterations, 4 chains, and 2 variables
## $mu: rvar&lt;100,4&gt;[3] mean ± sd:
## [1] 0.051 ± 0.11  0.111 ± 0.20  0.186 ± 0.31 
## 
## $Sigma: rvar&lt;100,4&gt;[3,3] mean ± sd:
##      [,1]          [,2]          [,3]         
## [1,]  1.28 ± 0.17   0.53 ± 0.20  -0.40 ± 0.28 
## [2,]  0.53 ± 0.20   3.67 ± 0.45  -2.10 ± 0.48 
## [3,] -0.40 ± 0.28  -2.10 ± 0.48   8.12 ± 0.95</code></pre>
<p>The <code><a href="../reference/draws_rvars.html">draws_rvars()</a></code> datatype works much the same way that other <code>draws</code> formats do; see the main package vignette at <code><a href="../articles/posterior.html">vignette("posterior")</a></code> for an introduction to <code>draws</code> objects. One difference is that <code>draws_rvars</code> counts variables differently, because it allows variables to be multidimensional. For example, the <code>post</code> object above contains two variables, <code>mu</code> and <code>Sigma</code>:</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/draws-index.html">variables</a></span><span class="op">(</span><span class="va">post</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "mu"    "Sigma"</code></pre>
<p>But converted to a <code><a href="../reference/draws_list.html">draws_list()</a></code>, it contains one variable for each combination of the dimensions of its variables:</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/draws-index.html">variables</a></span><span class="op">(</span><span class="fu"><a href="../reference/draws_list.html">as_draws_list</a></span><span class="op">(</span><span class="va">post</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "mu[1]"      "mu[2]"      "mu[3]"      "Sigma[1,1]" "Sigma[2,1]"
##  [6] "Sigma[3,1]" "Sigma[1,2]" "Sigma[2,2]" "Sigma[3,2]" "Sigma[1,3]"
## [11] "Sigma[2,3]" "Sigma[3,3]"</code></pre>
</div>
<div id="math-with-rvars" class="section level2">
<h2 class="hasAnchor">
<a href="#math-with-rvars" class="anchor"></a>Math with <code>rvar</code>s</h2>
<p>The <code><a href="../reference/rvar.html">rvar()</a></code> datatype implements most math operations, including basic arithmetic, functions in the <em>Math</em> and <em>Summary</em> groups, like <code><a href="https://rdrr.io/r/base/Log.html">log()</a></code> and <code><a href="https://rdrr.io/r/base/Log.html">exp()</a></code> (see <code><a href="https://rdrr.io/r/base/groupGeneric.html">help("groupGeneric")</a></code> for a list), and more. Binary operators can be performed between multiple <code>rvar</code>s or between <code>rvar</code>s and <code>numeric</code>s. A simple example:</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mu</span> <span class="op">&lt;-</span> <span class="va">post</span><span class="op">$</span><span class="va">mu</span>
<span class="va">Sigma</span> <span class="op">&lt;-</span> <span class="va">post</span><span class="op">$</span><span class="va">Sigma</span>

<span class="va">mu</span> <span class="op">+</span> <span class="fl">1</span></code></pre></div>
<pre><code>## rvar&lt;100,4&gt;[3] mean ± sd:
## [1] 1.1 ± 0.11  1.1 ± 0.20  1.2 ± 0.31</code></pre>
<p>Matrix multiplication is also implemented (using a tensor product under the hood). Because the normal matrix multiplication operator in R (<code><a href="https://rdrr.io/r/base/matmult.html">%*%</a></code>) cannot be properly implemented for S3 datatypes, <code>rvar</code> uses <code><a href="../reference/rvar-matmult.html">%**%</a></code> instead. A trivial example:</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Sigma</span> <span class="op">%**%</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## rvar&lt;100,4&gt;[3,3] mean ± sd:
##      [,1]          [,2]          [,3]         
## [1,]  1.28 ± 0.17   1.05 ± 0.40  -1.21 ± 0.85 
## [2,]  0.53 ± 0.20   7.33 ± 0.89  -6.30 ± 1.44 
## [3,] -0.40 ± 0.28  -4.20 ± 0.96  24.35 ± 2.84</code></pre>
<p>The set of mathematical functions and operators supported by <code>rvar</code>s includes:</p>
<table class="table">
<colgroup>
<col width="53%">
<col width="46%">
</colgroup>
<thead><tr class="header">
<th align="left">Group</th>
<th align="left">Functions and operators</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Arithmetic operators</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/Arithmetic.html">+</a></code>, <code><a href="https://rdrr.io/r/base/Arithmetic.html">-</a></code>, <code><a href="https://rdrr.io/r/base/Arithmetic.html">*</a></code>, <code><a href="https://rdrr.io/r/base/Arithmetic.html">/</a></code>, <code><a href="https://rdrr.io/r/base/Arithmetic.html">^</a></code>, <code><a href="https://rdrr.io/r/base/Arithmetic.html">%%</a></code>, <code><a href="https://rdrr.io/r/base/Arithmetic.html">%/%</a></code>
</td>
</tr>
<tr class="even">
<td align="left">Logical operators</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/Logic.html">&amp;</a></code>, <code><a href="https://rdrr.io/r/base/Logic.html">|</a></code>, <code><a href="https://rdrr.io/r/base/Logic.html">!</a></code>
</td>
</tr>
<tr class="odd">
<td align="left">Comparison operators</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/Comparison.html">==</a></code>, <code><a href="https://rdrr.io/r/base/Comparison.html">!=</a></code>, <code><a href="https://rdrr.io/r/base/Comparison.html">&lt;</a></code>, <code><a href="https://rdrr.io/r/base/Comparison.html">&lt;=</a></code>, <code><a href="https://rdrr.io/r/base/Comparison.html">&gt;=</a></code>, <code><a href="https://rdrr.io/r/base/Comparison.html">&gt;</a></code>
</td>
</tr>
<tr class="even">
<td align="left">Matrix multiplication</td>
<td align="left"><code><a href="../reference/rvar-matmult.html">%**%</a></code></td>
</tr>
<tr class="odd">
<td align="left">Basic functions</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/MathFun.html">abs()</a></code>, <code><a href="https://rdrr.io/r/base/sign.html">sign()</a></code><br><code><a href="https://rdrr.io/r/base/MathFun.html">sqrt()</a></code><br><code><a href="https://rdrr.io/r/base/Round.html">floor()</a></code>, <code><a href="https://rdrr.io/r/base/Round.html">ceiling()</a></code>, <code><a href="https://rdrr.io/r/base/Round.html">trunc()</a></code>, <code><a href="https://rdrr.io/r/base/Round.html">round()</a></code>, <code><a href="https://rdrr.io/r/base/Round.html">signif()</a></code>
</td>
</tr>
<tr class="even">
<td align="left">Logarithms and exponentials</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/Log.html">exp()</a></code>, <code><a href="https://rdrr.io/r/base/Log.html">expm1()</a></code><br><code><a href="https://rdrr.io/r/base/Log.html">log()</a></code>, <code><a href="https://rdrr.io/r/base/Log.html">log10()</a></code>, <code><a href="https://rdrr.io/r/base/Log.html">log2()</a></code>, <code><a href="https://rdrr.io/r/base/Log.html">log1p()</a></code>
</td>
</tr>
<tr class="odd">
<td align="left">Trigonometric functions</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/Trig.html">cos()</a></code>, <code><a href="https://rdrr.io/r/base/Trig.html">sin()</a></code>, <code><a href="https://rdrr.io/r/base/Trig.html">tan()</a></code><br><code><a href="https://rdrr.io/r/base/Trig.html">cospi()</a></code>, <code><a href="https://rdrr.io/r/base/Trig.html">sinpi()</a></code>, <code><a href="https://rdrr.io/r/base/Trig.html">tanpi()</a></code><br><code><a href="https://rdrr.io/r/base/Trig.html">acos()</a></code>, <code><a href="https://rdrr.io/r/base/Trig.html">asin()</a></code>, <code><a href="https://rdrr.io/r/base/Trig.html">atan()</a></code>
</td>
</tr>
<tr class="even">
<td align="left">Hyperbolic functions</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/Hyperbolic.html">cosh()</a></code>, <code><a href="https://rdrr.io/r/base/Hyperbolic.html">sinh()</a></code>, <code><a href="https://rdrr.io/r/base/Hyperbolic.html">tanh()</a></code><br><code><a href="https://rdrr.io/r/base/Hyperbolic.html">acosh()</a></code>, <code><a href="https://rdrr.io/r/base/Hyperbolic.html">asinh()</a></code>, <code><a href="https://rdrr.io/r/base/Hyperbolic.html">atanh()</a></code>
</td>
</tr>
<tr class="odd">
<td align="left">Special functions</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/Special.html">lgamma()</a></code>, <code><a href="https://rdrr.io/r/base/Special.html">gamma()</a></code>, <code><a href="https://rdrr.io/r/base/Special.html">digamma()</a></code>, <code><a href="https://rdrr.io/r/base/Special.html">trigamma()</a></code>
</td>
</tr>
<tr class="even">
<td align="left">Cumulative functions</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/cumsum.html">cumsum()</a></code>, <code><a href="https://rdrr.io/r/base/cumsum.html">cumprod()</a></code>, <code><a href="https://rdrr.io/r/base/cumsum.html">cummax()</a></code>, <code><a href="https://rdrr.io/r/base/cumsum.html">cummin()</a></code>
</td>
</tr>
<tr class="odd">
<td align="left">Array transposition</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/t.html">t()</a></code>, <code><a href="https://rdrr.io/r/base/aperm.html">aperm()</a></code>
</td>
</tr>
<tr class="even">
<td align="left">Matrix decomposition</td>
<td align="left"><code><a href="https://rdrr.io/r/base/chol.html">chol()</a></code></td>
</tr>
</tbody>
</table>
</div>
<div id="expectations-and-summary-functions" class="section level2">
<h2 class="hasAnchor">
<a href="#expectations-and-summary-functions" class="anchor"></a>Expectations and summary functions</h2>
<p>The <code><a href="../reference/rvar-summaries-over-draws.html">E()</a></code> function is an alias of <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, producing means within each cell of an <code>rvar</code>. For example, given <code>mu</code>:</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mu</span></code></pre></div>
<pre><code>## rvar&lt;100,4&gt;[3] mean ± sd:
## [1] 0.051 ± 0.11  0.111 ± 0.20  0.186 ± 0.31</code></pre>
<p>We can get the expectation of each cell of <code>mu</code>:</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/rvar-summaries-over-draws.html">E</a></span><span class="op">(</span><span class="va">mu</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.05139284 0.11132363 0.18581977</code></pre>
<p>Expectations of logical expressions are probabilities, and can be computed either with <code><a href="../reference/rvar-summaries-over-draws.html">E()</a></code> / <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> or with <code><a href="../reference/rvar-summaries-over-draws.html">Pr()</a></code>. <code><a href="../reference/rvar-summaries-over-draws.html">Pr()</a></code> is provided as notational sugar, but also checks that the input is a logical variable before taking the mean:</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/rvar-summaries-over-draws.html">Pr</a></span><span class="op">(</span><span class="va">mu</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.6600 0.6900 0.7025</code></pre>
<p>More generally, the <code>rvar</code> data type provides two types of summary functions:</p>
<ol style="list-style-type: decimal">
<li>
<p>Summary functions that mimic base-R vector summary functions, except applied to <code>rvar</code> vectors. These apply their summaries <strong>over</strong> elements of the input vectors <strong>within</strong> each draw, generally returning an <code>rvar</code> of length 1. These functions are prefixed with <code>rvar_</code> as a reminder that they return <code>rvar</code>s. Here is an example of <code><a href="../reference/rvar-summaries-within-draws.html">rvar_mean()</a></code>:</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/rvar-summaries-within-draws.html">rvar_mean</a></span><span class="op">(</span><span class="va">mu</span><span class="op">)</span></code></pre></div>
<pre><code>## rvar&lt;100,4&gt;[1] mean ± sd:
## [1] 0.12 ± 0.11</code></pre>
</li>
<li>
<p>Summary functions that summarise <strong>within</strong> elements of input vectors and <strong>over</strong> draws. These summary functions generally return base arrays (<code>numeric</code> or <code>logical</code>) of the same shape as the input <code>rvar</code>, and are especially useful for diagnostic summaries. These summary functions are not prefixed with <code>rvar_</code> as they do not return <code>rvar</code>s. Here is an example of <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>:</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mu</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.05139284 0.11132363 0.18581977</code></pre>
<p>You should expect the same values from these functions (though in a different shape) when you use them with <code><a href="../reference/draws_summary.html">summarise_draws()</a></code>, for example:</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/draws_summary.html">summarise_draws</a></span><span class="op">(</span><span class="va">mu</span>, <span class="va">mean</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   variable   mean
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 mu[1]    0.0514
## 2 mu[2]    0.111 
## 3 mu[3]    0.186</code></pre>
</li>
</ol>
<p>Here is a table of both types of summary functions:</p>
<table class="table">
<colgroup>
<col width="20%">
<col width="38%">
<col width="41%">
</colgroup>
<thead><tr class="header">
<th></th>
<th align="left">1. Summarise <em>within</em> draws,<br><em>over</em> elements</th>
<th align="left">2. Summarise <em>over</em> draws,<br><em>within</em> elements<br>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>
<strong>Output format</strong><br>of <code>res = f(x)</code>
</td>
<td align="left">
<code>rvar</code> of length 1</td>
<td align="left">
<code>array</code> of same shape as input <code>rvar</code>
</td>
</tr>
<tr class="even">
<td><strong>Help page</strong></td>
<td align="left"><code><a href="../reference/rvar-summaries-within-draws.html">help("rvar-summaries-within-draws")</a></code></td>
<td align="left"><code><a href="../reference/rvar-summaries-over-draws.html">help("rvar-summaries-over-draws")</a></code></td>
</tr>
<tr class="odd">
<td>Numeric summaries</td>
<td align="left">
<code><a href="../reference/rvar-summaries-within-draws.html">rvar_median()</a></code><br><code><a href="../reference/rvar-summaries-within-draws.html">rvar_sum()</a></code>, <code><a href="../reference/rvar-summaries-within-draws.html">rvar_prod()</a></code><br><code><a href="../reference/rvar-summaries-within-draws.html">rvar_min()</a></code>, <code><a href="../reference/rvar-summaries-within-draws.html">rvar_max()</a></code>
</td>
<td align="left">
<code><a href="https://rdrr.io/r/stats/median.html">median()</a></code><br><code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code>, <code><a href="https://rdrr.io/r/base/prod.html">prod()</a></code><br><code><a href="https://rdrr.io/r/base/Extremes.html">min()</a></code>, <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code>
</td>
</tr>
<tr class="even">
<td>Mean</td>
<td align="left">
<code><a href="../reference/rvar-summaries-within-draws.html">rvar_mean()</a></code><br><em>N/A</em>
</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, <code><a href="../reference/rvar-summaries-over-draws.html">E()</a></code><br><code><a href="../reference/rvar-summaries-over-draws.html">Pr()</a></code>: enforces that input is <code>logical</code>
</td>
</tr>
<tr class="odd">
<td>Spread</td>
<td align="left">
<code><a href="../reference/rvar-summaries-within-draws.html">rvar_sd()</a></code> <br><code><a href="../reference/rvar-summaries-within-draws.html">rvar_var()</a></code> <br><code><a href="../reference/rvar-summaries-within-draws.html">rvar_mad()</a></code>
</td>
<td align="left">
<code><a href="../reference/rvar-summaries-over-draws.html">sd()</a></code><br><code><a href="../reference/rvar-summaries-over-draws.html">var()</a></code>, <code><a href="https://pkg.mitchelloharawild.com/distributional/reference/variance.html">variance()</a></code><br><code><a href="../reference/rvar-summaries-over-draws.html">mad()</a></code>
</td>
</tr>
<tr class="even">
<td>Range</td>
<td align="left">
<code><a href="../reference/rvar-summaries-within-draws.html">rvar_range()</a></code><br><strong>Note:</strong> <code>length(res) == 2</code>
</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/range.html">range()</a></code><br><strong>Note:</strong> <code>dim(res) == c(2, dim(x))</code>
</td>
</tr>
<tr class="odd">
<td>Logical summaries</td>
<td align="left">
<code><a href="../reference/rvar-summaries-within-draws.html">rvar_all()</a></code>, <code><a href="../reference/rvar-summaries-within-draws.html">rvar_any()</a></code>
</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/all.html">all()</a></code>, <code><a href="https://rdrr.io/r/base/any.html">any()</a></code>
</td>
</tr>
<tr class="even">
<td>Special value predicates</td>
<td align="left">
<code><a href="../reference/rvar_is_finite.html">rvar_is_finite()</a></code><br><code><a href="../reference/rvar_is_finite.html">rvar_is_infinite()</a></code><br><code><a href="../reference/rvar_is_finite.html">rvar_is_nan()</a></code><br><code><a href="../reference/rvar_is_finite.html">rvar_is_na()</a></code><br><strong>Note:</strong> <code>dim(res) == dim(x)</code>. These functions act within draws but do not summarise over elements.</td>
<td align="left">
<code><a href="https://rdrr.io/r/base/is.finite.html">is.finite()</a></code><br><code><a href="https://rdrr.io/r/base/is.finite.html">is.infinite()</a></code><br><code><a href="https://rdrr.io/r/base/is.finite.html">is.nan()</a></code><br><code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code><br><strong>Note:</strong> <code>res[i] == TRUE</code> if <code>x[i]</code> has any draws matching predicate (except for <code><a href="https://rdrr.io/r/base/is.finite.html">is.finite()</a></code>, where all draws in <code>x[i]</code> must match)</td>
</tr>
<tr class="odd">
<td>Diagnostics</td>
<td align="left"><em>N/A</em></td>
<td align="left">
<code><a href="../reference/ess_basic.html">ess_basic()</a></code>, <code><a href="../reference/ess_bulk.html">ess_bulk()</a></code>, <code><a href="../reference/ess_quantile.html">ess_quantile()</a></code>, <code><a href="../reference/ess_sd.html">ess_sd()</a></code>, <code><a href="../reference/ess_tail.html">ess_tail()</a></code>,<br><code><a href="../reference/mcse_mean.html">mcse_mean()</a></code>, <code><a href="../reference/mcse_quantile.html">mcse_quantile()</a></code>, <code><a href="../reference/mcse_sd.html">mcse_sd()</a></code><br><code><a href="../reference/rhat.html">rhat()</a></code>, <code><a href="../reference/rhat_basic.html">rhat_basic()</a></code>
</td>
</tr>
</tbody>
</table>
</div>
<div id="constants" class="section level2">
<h2 class="hasAnchor">
<a href="#constants" class="anchor"></a>Constants</h2>
<p>Constant <code>rvar</code>s can be constructed by converting numeric vectors or arrays into <code>rvar</code>s using <code><a href="../reference/as_rvar.html">as_rvar()</a></code>, which will return an <code>rvar</code> with one draw and the same dimensions as its input:</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">const</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/as_rvar.html">as_rvar</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">)</span>
<span class="va">const</span></code></pre></div>
<pre><code>## rvar&lt;1&gt;[3] mean ± sd:
## [1] 1 ± NA  2 ± NA  3 ± NA</code></pre>
<p>While normally <code>rvar</code>s must have the same number of draws to be used in the same expression, <code>rvar</code>s with one draw are treated like constants, and can be combined with other <code>rvar</code>s:</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mu</span> <span class="op">+</span> <span class="va">const</span></code></pre></div>
<pre><code>## rvar&lt;100,4&gt;[3] mean ± sd:
## [1] 1.1 ± 0.11  2.1 ± 0.20  3.2 ± 0.31</code></pre>
</div>
<div id="using-existing-r-functions-and-expressions-with-rvars" class="section level2">
<h2 class="hasAnchor">
<a href="#using-existing-r-functions-and-expressions-with-rvars" class="anchor"></a>Using existing R functions and expressions with <code>rvar</code>s</h2>
<p>While <code>rvar</code>s attempt to emulate as much of the functionality of base R arrays as possible, there are situations in which an existing R function may not work directly with an <code>rvar</code>. There are several approaches to solving this problem.</p>
<p>For example, say you wish to generate samples from the following expression for <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma\)</span>, and <span class="math inline">\(x\)</span>:</p>
<p><span class="math display">\[
\begin{align}
\left[\begin{matrix}\mu_1 \\ \vdots \\ \mu_4 \end{matrix}\right] &amp;\sim \textrm{Normal}\left(\left[\begin{matrix}1 \\ \vdots \\ 4 \end{matrix}\right],1\right)\\
\sigma &amp;\sim \textrm{Gamma}(1,1)\\
\left[\begin{matrix}x_1 \\ \vdots \\ x_4 \end{matrix}\right] &amp;\sim \textrm{Normal}\left(\left[\begin{matrix}\mu_1 \\ \vdots \\ \mu_4 \end{matrix}\right], \sigma\right)
\end{align}
\]</span></p>
<p>There are three different approaches you might take to doing this: converting existing R functions with <code><a href="../reference/rfun.html">rfun()</a></code>, executing expressions of random variables with <code><a href="../reference/rdo.html">rdo()</a></code>, or evaluating random number generator functions using <code><a href="../reference/rvar_rng.html">rvar_rng()</a></code>.</p>
<div id="converting-functions-with-rfun" class="section level3">
<h3 class="hasAnchor">
<a href="#converting-functions-with-rfun" class="anchor"></a>Converting functions with <code>rfun()</code>
</h3>
<p>The <code><a href="../reference/rfun.html">rfun()</a></code> wrapper converts an existing R function into a new function that <code>rvar</code>s can be passed to it as arguments, and which will return <code>rvar</code>s. We can use <code><a href="../reference/rfun.html">rfun()</a></code> to convert the base <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> and <code><a href="https://rdrr.io/r/stats/GammaDist.html">rgamma()</a></code> random number generating functions into functions that accept and return <code>rvar</code>s:</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">rvar_norm</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rfun.html">rfun</a></span><span class="op">(</span><span class="va">rnorm</span><span class="op">)</span>
<span class="va">rvar_gamma</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rfun.html">rfun</a></span><span class="op">(</span><span class="va">rgamma</span><span class="op">)</span></code></pre></div>
<p>Then we can translate the above example into code using those functions:</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fu">rvar_norm</span><span class="op">(</span><span class="fl">4</span>, mean <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fu">rvar_gamma</span><span class="op">(</span><span class="fl">1</span>, shape <span class="op">=</span> <span class="fl">1</span>, rate <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="va">x</span> <span class="op">&lt;-</span> <span class="fu">rvar_norm</span><span class="op">(</span><span class="fl">4</span>, <span class="va">mu</span>, <span class="va">sigma</span><span class="op">)</span>
<span class="va">x</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[4] mean ± sd:
## [1] 1 ± 1.7  2 ± 1.8  3 ± 1.8  4 ± 1.8</code></pre>
<p>While <code><a href="../reference/rfun.html">rfun()</a></code>-converted functions work well for prototyping, they will generally speaking be slower than functions designed specifically for <code>rvar</code>s. Thus, you may find you need to adopt other strategies (like <code><a href="../reference/rvar_rng.html">rvar_rng()</a></code>, described below; or re-writing functions to support <code>rvar</code> directly using math operators and/or the <code><a href="../reference/draws_of.html">draws_of()</a></code> function).</p>
</div>
<div id="evaluating-expressions-with-rdo" class="section level3">
<h3 class="hasAnchor">
<a href="#evaluating-expressions-with-rdo" class="anchor"></a>Evaluating expressions with <code>rdo()</code>
</h3>
<p>An alternative to <code><a href="../reference/rfun.html">rfun()</a></code> is to use <code><a href="../reference/rdo.html">rdo()</a></code>, which can be passed nearly-arbitrary R expressions. The expression will be executed multiple times to construct an <code>rvar</code>. E.g., we can write an expression for <code>mu</code> like in the above example:</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rdo.html">rdo</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">4</span>, mean <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">mu</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[4] mean ± sd:
## [1] 0.99 ± 1.00  1.96 ± 0.99  3.02 ± 1.00  4.03 ± 1.01</code></pre>
<p>We can also control the number of draws using the <code>ndraws</code> argument:</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rdo.html">rdo</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">4</span>, mean <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, ndraws <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span>
<span class="va">mu</span></code></pre></div>
<pre><code>## rvar&lt;1000&gt;[4] mean ± sd:
## [1] 0.99 ± 0.97  2.04 ± 1.02  2.98 ± 1.00  3.99 ± 0.98</code></pre>
<p><code><a href="../reference/rdo.html">rdo()</a></code> expressions can also contain other <code>rvar</code>s, so long as all <code>rvar</code>s in the expression have the same number of draws. Thus, we can re-write the example above that used <code><a href="../reference/rfun.html">rfun()</a></code> as follows:</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rdo.html">rdo</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">4</span>, mean <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rdo.html">rdo</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/GammaDist.html">rgamma</a></span><span class="op">(</span><span class="fl">1</span>, shape <span class="op">=</span> <span class="fl">1</span>, rate <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rdo.html">rdo</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">4</span>, <span class="va">mu</span>, <span class="va">sigma</span><span class="op">)</span><span class="op">)</span>
<span class="va">x</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[4] mean ± sd:
## [1] 0.95 ± 1.8  1.99 ± 1.7  2.98 ± 1.7  3.98 ± 1.7</code></pre>
<p>Like <code><a href="../reference/rfun.html">rfun()</a></code>, <code><a href="../reference/rdo.html">rdo()</a></code> is not necessarily fast, so you may find it more useful for prototyping than production code.</p>
</div>
<div id="evaluating-random-number-generators-with-rvar_rng" class="section level3">
<h3 class="hasAnchor">
<a href="#evaluating-random-number-generators-with-rvar_rng" class="anchor"></a>Evaluating random number generators with <code>rvar_rng()</code>
</h3>
<p><code><a href="../reference/rvar_rng.html">rvar_rng()</a></code> is an alternative to <code><a href="../reference/rfun.html">rfun()</a></code>/<code><a href="../reference/rdo.html">rdo()</a></code> designed specifically to work with random number generating functions that follow the typical API of such functions in base R. Such functions, like <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code>, <code><a href="https://rdrr.io/r/stats/GammaDist.html">rgamma()</a></code>, <code><a href="https://rdrr.io/r/stats/Binomial.html">rbinom()</a></code>, etc all following this interface:</p>
<ul>
<li>They have a first argument, <code>n</code>, giving the number of draws to take from the distribution.</li>
<li>Their arguments for distribution parameters (<code>mean</code>, <code>sd</code>, <code>shape</code>, <code>rate</code>, etc.) are vectorized.</li>
<li>They return a single vector of length <code>n</code>, representing <code>n</code> draws from the distribution.</li>
</ul>
<p>You can use any function with this interface with <code><a href="../reference/rvar_rng.html">rvar_rng()</a></code>, and it will adapt it to be able to take <code>rvar</code> arguments and return an <code>rvar</code>, as follows:</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rvar_rng.html">rvar_rng</a></span><span class="op">(</span><span class="va">rnorm</span>, <span class="fl">4</span>, mean <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rvar_rng.html">rvar_rng</a></span><span class="op">(</span><span class="va">rgamma</span>, <span class="fl">1</span>, shape <span class="op">=</span> <span class="fl">1</span>, rate <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rvar_rng.html">rvar_rng</a></span><span class="op">(</span><span class="va">rnorm</span>, <span class="fl">4</span>, <span class="va">mu</span>, <span class="va">sigma</span><span class="op">)</span>
<span class="va">x</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[4] mean ± sd:
## [1] 1 ± 1.6  2 ± 1.7  3 ± 1.7  4 ± 1.7</code></pre>
<p>In contrast to the <code><a href="../reference/rfun.html">rfun()</a></code> and <code><a href="../reference/rdo.html">rdo()</a></code> examples above, <code><a href="../reference/rvar_rng.html">rvar_rng()</a></code> takes advantage of the existing vectorization of the underlying random number generating function to execute quickly.</p>
</div>
</div>
<div id="broadcasting" class="section level2">
<h2 class="hasAnchor">
<a href="#broadcasting" class="anchor"></a>Broadcasting</h2>
<p>Broadcasting for <code>rvar</code>s does not follow R’s vector recycling rules. Instead, when two variables with different dimensions are being used with basic arithmetic functions, dimensions are added until both variables have the same number of dimensions. If two variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> differ on the length of dimension <span class="math inline">\(d\)</span>, they can be broadcast to the same size so long as one of the variables has dimension <span class="math inline">\(d\)</span> of size 1. Then that variable will be broadcast up to the same size as the other variable along that dimension. If two variables disagree on the size of a dimension and neither has size 1, it is an error.</p>
<p>For example, consider this random matrix:</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rdo.html">rdo</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">12</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">12</span><span class="op">)</span>, dim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span>
<span class="va">X</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[4,3] mean ± sd:
##      [,1]          [,2]          [,3]         
## [1,]  0.99 ± 0.99   5.02 ± 1.01   9.02 ± 1.01 
## [2,]  2.03 ± 1.03   6.00 ± 1.00  10.03 ± 0.99 
## [3,]  3.00 ± 1.00   7.03 ± 1.01  11.00 ± 1.02 
## [4,]  4.01 ± 0.99   8.01 ± 1.02  12.00 ± 1.00</code></pre>
<p>And this vector of length 3:</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rdo.html">rdo</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">:</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">y</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[3] mean ± sd:
## [1] 3 ± 1  2 ± 1  1 ± 1</code></pre>
<p>If we attempt to add <code>X</code> and <code>y</code>, it will produce an error as vectors are by default treated as column vectors, and <code>y</code> has length 3 while columns of <code>X</code> have length 4:</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">X</span> <span class="op">+</span> <span class="va">y</span></code></pre></div>
<pre><code>## Error: Cannot broadcast array of shape [4000,3,1] to array of shape [4000,4,3]:
## All dimensions must be 1 or equal.</code></pre>
<p>By contrast, R arrays of the same shape will simply recycle <code>y</code> until it is the same length as <code>X</code> (regardless of the dimensions). Thus will produce a result, though likely not the intended result:</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></code></pre></div>
<pre><code>##          [,1]      [,2]     [,3]
## [1,] 3.992307  7.011170 10.01719
## [2,] 4.022329  6.992647 13.03050
## [3,] 3.992297 10.031501 12.99773
## [4,] 7.008743 10.003724 12.99064</code></pre>
<p>On the other hand, if y were a row vector…</p>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">row_y</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span>
<span class="va">row_y</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[1,3] mean ± sd:
##      [,1]   [,2]   [,3]  
## [1,] 3 ± 1  2 ± 1  1 ± 1</code></pre>
<p>…it would have the same number of columns as <code>X</code> and contain only one row, so it can be broadcast along rows of <code>X</code>:</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">X</span> <span class="op">+</span> <span class="va">row_y</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[4,3] mean ± sd:
##      [,1]      [,2]      [,3]     
## [1,]  4 ± 1.4   7 ± 1.4  10 ± 1.4 
## [2,]  5 ± 1.4   8 ± 1.4  11 ± 1.4 
## [3,]  6 ± 1.4   9 ± 1.4  12 ± 1.4 
## [4,]  7 ± 1.4  10 ± 1.4  13 ± 1.4</code></pre>
</div>
<div id="applying-functions-over-rvars" class="section level2">
<h2 class="hasAnchor">
<a href="#applying-functions-over-rvars" class="anchor"></a>Applying functions over <code>rvar</code>s</h2>
<p>The <code>rvar</code> data type supplies an implementation of <code><a href="https://rdrr.io/r/base/list.html">as.list()</a></code>, which should give compatibility with the base R family of functions for applying functions over arrays: <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>, <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code>, <code><a href="https://rdrr.io/r/base/lapply.html">vapply()</a></code>, <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code>, etc. You can also manually use <code><a href="https://rdrr.io/r/base/list.html">as.list()</a></code> to convert an <code>rvar</code> into a list along its first dimension, which may be necessary for compatibility with some functions (like <code>purrr:map()</code>).</p>
<p>For example, given this multidimensional <code>rvar</code>…</p>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">3456</span><span class="op">)</span>
<span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/rvar_rng.html">rvar_rng</a></span><span class="op">(</span><span class="va">rnorm</span>, <span class="fl">24</span>, mean <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">24</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">4</span><span class="op">)</span>
<span class="va">x</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[2,3,4] mean ± sd:
## , , 1
## 
##      [,1]       [,2]       [,3]      
## [1,]  1 ± 0.99   3 ± 0.98   5 ± 1.00 
## [2,]  2 ± 1.01   4 ± 0.99   6 ± 1.00 
## 
## , , 2
## 
##      [,1]       [,2]       [,3]      
## [1,]  7 ± 1.00   9 ± 0.99  11 ± 1.00 
## [2,]  8 ± 1.00  10 ± 1.00  12 ± 1.00 
## 
## , , 3
## 
##      [,1]       [,2]       [,3]      
## [1,] 13 ± 1.00  15 ± 1.03  17 ± 0.99 
## [2,] 14 ± 1.00  16 ± 0.98  18 ± 1.00 
## 
## , , 4
## 
##      [,1]       [,2]       [,3]      
## [1,] 19 ± 0.99  21 ± 0.99  23 ± 1.02 
## [2,] 20 ± 1.00  22 ± 0.99  24 ± 1.01</code></pre>
<p>… you can apply functions along the margins using <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> (here, a silly example):</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">x</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span>, <span class="va">length</span><span class="op">)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    4    4    4
## [2,]    4    4    4</code></pre>
<p>One exception is that while <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> will work with an <code>rvar</code> input if your function returns base data types (like numerics), it will not give you simplified <code>rvar</code> arrays if your function returns an <code>rvar</code>. Thus, we supply the <code><a href="../reference/rvar_apply.html">rvar_apply()</a></code> function, which takes in either base arrays or <code>rvar</code> arrays and returns <code>rvar</code> arrays, and which also uses the <code>rvar</code> broadcasting rules to combine the results of the applied function.</p>
<p>For example, you can use <code><a href="../reference/rvar_apply.html">rvar_apply()</a></code> with <code><a href="../reference/rvar-summaries-within-draws.html">rvar_mean()</a></code> to compute the distributions of means along one margin of an array:</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/rvar_apply.html">rvar_apply</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">1</span>, <span class="va">rvar_mean</span><span class="op">)</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[2] mean ± sd:
## [1] 12 ± 0.29  13 ± 0.29</code></pre>
<p>Or along multiple dimensions:</p>
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/rvar_apply.html">rvar_apply</a></span><span class="op">(</span><span class="va">x</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span><span class="op">)</span>, <span class="va">rvar_mean</span><span class="op">)</span></code></pre></div>
<pre><code>## rvar&lt;4000&gt;[3,4] mean ± sd:
##      [,1]         [,2]         [,3]         [,4]        
## [1,]  1.5 ± 0.71   7.5 ± 0.70  13.5 ± 0.71  19.5 ± 0.71 
## [2,]  3.5 ± 0.69   9.5 ± 0.70  15.5 ± 0.71  21.5 ± 0.70 
## [3,]  5.5 ± 0.71  11.5 ± 0.70  17.5 ± 0.70  23.5 ± 0.72</code></pre>
</div>
<div id="using-rvars-in-data-frames-and-in-ggplot2" class="section level2">
<h2 class="hasAnchor">
<a href="#using-rvars-in-data-frames-and-in-ggplot2" class="anchor"></a>Using <code>rvar</code>s in data frames and in ggplot2</h2>
<p><code>rvar</code>s can be used as columns in <code><a href="https://rdrr.io/r/base/data.frame.html">data.frame()</a></code> or <code>tibble()</code> objects:</p>
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"a"</span>,<span class="st">"b"</span>,<span class="st">"c"</span><span class="op">)</span>, <span class="va">y</span><span class="op">)</span></code></pre></div>
<pre><code>##   x                   y
## 1 a 2.997811 ± 1.028742
## 2 b 1.992926 ± 1.011693
## 3 c 0.995190 ± 1.001205</code></pre>
<p>This makes them convenient for adding predictions to a data frame alongside the data used to generate the predictions. <code>rvar</code>s can then be visualized with ggplot2 using the <code>stat_dist_...</code> family of geometries in the <a href="https://mjskay.github.io/ggdist/">ggdist</a> package.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Paul-Christian Bürkner, Jonah Gabry, Matthew Kay, Aki Vehtari.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
