on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest, r: "devel", suggested_check: TRUE }
          - { os: macOS-latest, r: "release", suggested_check: TRUE }
          - { os: windows-latest, r: "release", suggested_check: TRUE }
          - { os: ubuntu-latest, r: "devel", suggested_check: TRUE }
          - { os: ubuntu-latest, r: "release", suggested_check: TRUE }
          - { os: ubuntu-latest, r: "oldrel", suggested_check: FALSE }
          - { os: ubuntu-latest, r: "3.6", suggested_check: FALSE }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DEPS_MODE: ${{ matrix.config.suggested_check && 'all' || 'hard' }}

    steps:
      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::knitr, any::rmarkdown
          dependencies: 'Sys.getenv("DEPS_MODE")'
          needs: check

      - name: Session info
        run: |
          options(width = 100)
          sessioninfo::session_info(installed.packages()[, "Package"], include_base = TRUE)
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
