name: Continuous Benchmarks (Comment)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Continuous Benchmarks (Receive)"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - uses: lorenzwalthert/touchstone/actions/comment@a02c45d24459777f4bbed5e5cc0c94571799f51f
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
